pipeline{
    agent{
        label "jenkins-ssh-agent"

    }
    stages{
        stage("Git Checkout"){
            steps{
                git credentialsId: "github" url:"https://github.com/Suraj01Dev/Jenkins-Examples/tree/master/java_sample_setup"
            }
        }
    }
}